import type {
  ExternalResourceSource,
  NormalizedExternalResource,
  ProviderValidationResult,
  TranscriptResult,
} from "@ruach/shared-types";
import type { ResourceProvider } from "./ResourceProvider";
import { parseVimeoUrl } from "./url-parsing";

/** No network calls. See MockYouTubeProvider for the same determinism rationale. */
export class MockVimeoProvider implements ResourceProvider {
  async validateUrl(url: string): Promise<ProviderValidationResult> {
    const videoId = parseVimeoUrl(url);
    if (!videoId) {
      return { valid: false, provider: null, externalId: null, reason: "Not a recognized Vimeo URL." };
    }
    return { valid: true, provider: "VIMEO", externalId: videoId, reason: null };
  }

  async getResource(source: ExternalResourceSource): Promise<NormalizedExternalResource> {
    return {
      sourceProvider: "VIMEO",
      externalId: source.externalId,
      resourceType: "VIDEO",
      title: `[MOCK] Vimeo video ${source.externalId}`,
      description: "Mock description generated by MockVimeoProvider for local development.",
      creatorName: "Mock Vimeo Account",
      publishedAt: new Date("2026-02-01T00:00:00Z"),
      durationSeconds: 900,
      thumbnailUrl: null,
      publicUrl: `https://vimeo.com/${source.externalId}`,
      embedUrl: `https://player.vimeo.com/video/${source.externalId}`,
      captionsAvailable: false,
    };
  }

  async getTranscript(_source: ExternalResourceSource): Promise<TranscriptResult | null> {
    return null;
  }
}
