import type {
  DiscoveredDocument,
  ExternalResourceSource,
  NormalizedExternalResource,
  ProviderValidationResult,
  TranscriptResult,
} from "@ruach/shared-types";
import type { ProviderConfiguration, ResourceProvider } from "./ResourceProvider";
import { parseYouTubeChannelUrl, parseYouTubeUrl } from "./url-parsing";

const KNOWN_MOCK_VIDEOS: Record<string, { title: string; description: string; creator: string; duration: number }> = {
  "mock-yt-anxiety-01": {
    title: "[FICTIONAL] Finding Peace When Anxiety Feels Constant",
    description: "A message on practical steps for facing anxious thoughts.",
    creator: "Riverside Fellowship",
    duration: 1860,
  },
  "mock-yt-forgiveness-01": {
    title: "[FICTIONAL] What Forgiveness Actually Requires",
    description: "Untangling forgiveness from reconciliation and excusing harm.",
    creator: "Riverside Fellowship",
    duration: 2220,
  },
};

/**
 * No network calls, ever. Deterministic given the same video ID so tests and demos are
 * reproducible. Unknown IDs still resolve (to a synthetic-but-plausible result) so a
 * developer can paste any youtube.com/watch?v=... URL during the import demo and get a
 * usable result, matching brief §57's "repository must run without production credentials."
 */
export class MockYouTubeProvider implements ResourceProvider {
  async validateUrl(url: string): Promise<ProviderValidationResult> {
    const videoId = parseYouTubeUrl(url);
    if (!videoId) {
      return { valid: false, provider: null, externalId: null, reason: "Not a recognized YouTube URL." };
    }
    return { valid: true, provider: "YOUTUBE", externalId: videoId, reason: null };
  }

  async getResource(source: ExternalResourceSource): Promise<NormalizedExternalResource> {
    const known = KNOWN_MOCK_VIDEOS[source.externalId];
    return {
      sourceProvider: "YOUTUBE",
      externalId: source.externalId,
      resourceType: "SERMON",
      title: known?.title ?? `[MOCK] YouTube video ${source.externalId}`,
      description: known?.description ?? "Mock description generated by MockYouTubeProvider for local development.",
      creatorName: known?.creator ?? "Mock Channel",
      publishedAt: new Date("2026-01-15T00:00:00Z"),
      durationSeconds: known?.duration ?? 1200,
      thumbnailUrl: `https://i.ytimg.com/vi/${source.externalId}/hqdefault.jpg`,
      publicUrl: `https://www.youtube.com/watch?v=${source.externalId}`,
      embedUrl: `https://www.youtube-nocookie.com/embed/${source.externalId}`,
      captionsAvailable: true,
    };
  }

  async getTranscript(source: ExternalResourceSource): Promise<TranscriptResult | null> {
    return {
      text:
        `Mock transcript for YouTube video ${source.externalId}. In a real integration this would come from ` +
        "the YouTube Data API's caption track. This placeholder exists so the categorization and retrieval " +
        "pipeline can be exercised end-to-end without any live credentials.",
      source: "PROVIDER_CAPTIONS",
      language: "en",
    };
  }

  async getSupportingDocuments(_source: ExternalResourceSource): Promise<DiscoveredDocument[]> {
    return [];
  }

  /** Deterministic, no network calls -- returns a fixed set of synthetic videos for any valid channel URL. */
  async listResources(configuration: ProviderConfiguration): Promise<NormalizedExternalResource[]> {
    if (!configuration.channelUrl || !parseYouTubeChannelUrl(configuration.channelUrl)) {
      throw new Error(`"${configuration.channelUrl}" doesn't look like a YouTube channel URL.`);
    }
    const mockIds = ["mock-yt-channel-01", "mock-yt-channel-02", "mock-yt-channel-03"];
    return Promise.all(mockIds.map((id) => this.getResource({ provider: "YOUTUBE", externalId: id, url: "" })));
  }
}
